build:
    environment:
        php: 7.2.13
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            tests:
                override:
                    - command: ./vendor/bin/codecept run --coverage-xml --coverage-phpunit coverage.clover
                      coverage:
                        file: ./tests/_output/coverage.xml
                        format: clover
filter:
    excluded_paths:
        - 'tests/*'
        - 'src/iexts/*'
    dependency_paths:
        - "vendor/"
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
tools:
    php_code_coverage:
        enabled: true
    external_code_coverage:
        timeout: 3600
