build:
    environment:
        php: 7.3.9
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
filter:
    excluded_paths:
        - "tests/*"
        - "src/iextensions/*"
    dependency_paths:
        - "vendor/"
tools:
    php_mess_detector: true
    php_code_sniffer: true
    php_pdepend: true
    external_code_coverage:
        timeout: 3600
