build:
    environment:
        php: 7.2.13
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'src/iexts/*'
    dependency_paths:
        - "vendor/"
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false