language: php
dist: trusty
matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: nightly

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - composer require codeception/codeception 3.0.x-dev

notifications:
  email:
    recipients:
    - 2317216477@qq.com
    on_success: always
    on_failure: always
