language: php
dist: trusty
matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

install:
  - composer require phpunit/phpunit ~4.0
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover
after_scripts:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    recipients:
    - 2317216477@qq.com
    on_success: always
    on_failure: never
