language: php
dist: trusty
matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.1
    - php: nightly

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - composer require codeception/codeception 3.0.x-dev
script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then ./vendor/bin/codecept run --coverage-text --coverage-phpunit coverage.clover; fi
after_scripts:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
notifications:
  email:
    recipients:
    - 2317216477@qq.com
    on_success: always
    on_failure: always
