language: php

sudo: required

notifications:
  email:
    recipients:
    - 2317216477@qq.com
    on_success: never
    on_failure: always

env:
  global:
    - TASK_TESTS_PHP=1
    - TASK_TESTS_COVERAGE=0
    - PHPUNIT_EXCLUDE_GROUP=mssql,oci,wincache,xcache,zenddata,cubrid
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env:
        - TASK_TESTS_COVERAGE=1
        - PHPUNIT_EXCLUDE_GROUP=oci,wincache,xcache,zenddata,cubrid
    - php: 7.2
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - php --version
  - composer --version
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi
install:
  - |
    if [ $TASK_TESTS_COVERAGE != 1 ]; then
      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - composer require phpunit/phpunit 4.8.36
script:
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --exclude-group $PHPUNIT_EXCLUDE_GROUP
    fi
after_success:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi