language: php
dist: trusty
matrix:
  fast_finish: true
  include:
    - php: 7.3.9
    - php: nightly

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - if [ $(phpenv version-name) == "7.3.9" ]; then composer require codeception/codeception 3.1.2; fi
before_script:
  - if [ $(phpenv version-name) == "7.3.9" ]; then chmod -R 777 ./runtime; fi
script:
  - if [ $(phpenv version-name) == "7.3.9" ]; then ./vendor/bin/codecept run --coverage-xml coverage.xml; fi
after_script:
  - if [ $(phpenv version-name) == "7.3.9" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) == "7.3.9" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml; fi
notifications:
  email:
    recipients:
    - 2317216477@qq.com
    on_success: always
    on_failure: always
