language: php
dist: trusty
matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: nightly

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - composer require codeception/codeception 3.0.x-dev
script:
  - ./vendor/bin/codecept run --coverage-xml --coverage-phpunit coverage.clover
after_scripts:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    recipients:
    - 2317216477@qq.com
    on_success: always
    on_failure: always
