language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
      env:
        - CODECEPTION_TEST=1
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

install:
  - composer install --prefer-dist --optimize-autoloader --quiet --no-interaction
  - |
    if [[$CODECEPTION_TEST == 1]]; then
    composer require codeception/codeception@3.0.x-dev
    fi

notifications:
  email:
    recipients:
    - 2317216477@qq.com
    on_success: always
    on_failure: never

script:
  - |
    if [[$CODECEPTION_TEST == 1]]; then
    ./vendor/bin/codecept run
    fi
