language: php
dist: trusty
matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

install:
  - composer require phpunit/phpunit ~4.0
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - 2317216477@qq.com
    on_success: always
    on_failure: never
