language: php
dist: trusty
matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then composer require codeception/codeception 3.0.x-dev; fi
script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then ./vendor/bin/codecept run; fi
notifications:
  email:
    recipients:
    - 2317216477@qq.com
    on_success: always
    on_failure: always
