language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

install:
  - composer install --prefer-dist --optimize-autoloader --quiet --no-interaction

notifications:
  email:
    recipients:
    - 2317216477@qq.com
    on_success: never
    on_failure: always